### ISSUE TITLE
Has the jar been published since v0.10?

### ISSUE THREAD

**Issue by mlockery** [conduktor/kafka-security-manager#102]
Hi,

I was wondering if the jar has been published since v0.10? 

I was previously bringing in kafka-security-manager_2.12 as a dependency to my project with:

```
    <dependency>
      <groupId>com.github.simplesteph.ksm</groupId>
      <artifactId>kafka-security-manager_2.12</artifactId>
      <version>0.9-SNAPSHOT</version>
    </dependency>
```

    and 

```
  <repositories>
    <repository>
      <id>beyondthelines</id>
      <url>https://dl.bintray.com/beyondthelines/maven/</url>
    </repository>
    <repository>
      <id>sonatypes-repo</id>
      <url>https://oss.sonatype.org/content/groups/public/</url>
    </repository>
  </repositories>
```

This (0.9-SNAPSHOT) has stopped working due to the grpc dependency issue, but I am unable to find version 0.11.0-SNAPSHOT or 0.10, even after changing the groupId to com.github.conduktor.ksm.

Are you able to publish these new versions if this has not been done?

Apologies if this is just me doing something wrong.

Thanks,
Mark

**Comment by simplesteph** [comment]
Should be fixed now, sorry for the delay :)

https://repo1.maven.org/maven2/io/conduktor/kafka-security-manager_2.12/0.11/

Try

```
<dependency>
      <groupId>io.conduktor</groupId>
      <artifactId>kafka-security-manager_2.12</artifactId>
      <version>0.11</version>
    </dependency>
```
