### ISSUE TITLE
Unable to extract the ACLs to S3

### ISSUE THREAD

**Issue by ritheshrithu** [conduktor/kafka-security-manager#112]
Hi Team,I have deployed ksm in Kubernetes using helm. I am providing all the parameters for extracting,

I could see the ACLs are being printed in logs, but not in the S3.

Below are the parameters passed as env variables.

SOURCE_S3_REGION : EU
SOURCE_S3_OBJECTKEY : kafka-security-manager/acls.csv
SOURCE_S3_BUCKETNAME | xyz
SOURCE_CLASS : io.conduktor.ksm.source.S3SourceAcl
KSM_EXTRACT_FORMAT:  csv
KSM_EXTRACT_ENABLE : true
AWS_SECRET_ACCESS_KEY : xyz
AWS_ACCESS_KEY_ID : xyz
AUTHORIZER_ZOOKEEPER_CONNECT: zoo:2181

Thanks in Advance.

Regards,
Rithesh S

**Comment by simplesteph** [comment]
exporting is only done to the console, which you can then save as a CSV

https://github.com/conduktor/kafka-security-manager#extracting-acls
