### ISSUE TITLE
Multiple Kafka cluster on the same zookeeper

### ISSUE THREAD

**Issue by hekme5** [conduktor/kafka-security-manager#113]
Can I have multiple zookeeper connect string as authorizer?
I added them as 'AUTHORIZER_ZOOKEEPER_CONNECT: zookeeper:2181,zookeeper:2181/kafka-test' but it seems to only update the last string. Is there a way to update both automatically?
Thank you

**Comment by simplesteph** [comment]
that's not how the ZK clients work.

`zoo1:2181,zoo2:2181/kafka` will connect to `/kafka` on `zoo1` and `zoo2`. If you need multiple clusters, deploy multiple KSM

**Comment by hekme5** [comment]
No, I am using the same zookeeper for multiple Kafka cluster. Will it be possible to use the same KSM?

**Comment by simplesteph** [comment]
yes you can, just deploy multiple KSM, one for each cluster.... 

One KSM instance:
`AUTHORIZER_ZOOKEEPER_CONNECT: zookeeper:2181/kafka1`

Another KSM instance:
`AUTHORIZER_ZOOKEEPER_CONNECT: zookeeper:2181/kafka2`
