### ISSUE TITLE
MSK IAM support

### ISSUE THREAD

**Issue by ivan-santos-eq** [conduktor/kafka-security-manager#130]
Howdy! would this project work with IAM auth (AWS) for MSK?

ref: https://github.com/aws/aws-msk-iam-auth

**Comment by simplesteph** [comment]
No unfortunately because the ACLs of Kafka for IAM security are managed outside of Kafka. It would need a special module for that

**Comment by ivan-santos-eq** [comment]
Hi @simplesteph I guess I was wondering if you could/need/use IAM auth to create ACLS for SCRAM users.

**Comment by ivan-santos-eq** [comment]
I found that it wide open and will not work out with IAM auth.
