### ISSUE TITLE
Problem building project, missing dependency in build.sbt

### ISSUE THREAD

**Issue by 7crmbs2** [conduktor/kafka-security-manager#98]
I got problems building the project.

I’m running
`sbt clean test \
&& sbt universal:stage`

Then I get this error message:
`sbt.librarymanagement.ResolveException: unresolved dependency: beyondthelines#grpcgatewaygenerator_2.12;0.0.9: not found`

Seems like [grpcgatewaygenerator](https://bintray.com/beyondthelines/maven/grpcgatewaygenerator/_latestVersion) has been deleted.

How can I solve this problem?
Is this something that can be fixed upstream?

**Comment by simplesteph** [comment]
fixed :)
